url: https://dbb-m.github.io
baseurl: /Hatirat
source-code: https://github.com/DBB-M/Hatirat

title: Hatırat Portalı
tagline: Türk Hatırat Yazarlığı Dijital Kataloğu
description: "Bu katalog, Türkiye'deki hatırat yazarlığını yazar, tür, dönem ve mekâna göre aranabilir biçimde sunar."
keywords: hatırat; anı; Türkiye; dijital beşeri bilimler
author: DBB

metadata: hatirat_cb_ready

organization-name: "DBB - Dijital Beşeri Bilimler"
organization-link: https://github.com/DBB-M
organization-logo-banner: /Hatirat/objects/dbb_dariah.jpg
organization-logo-nav:/Hatirat/objects/dbb_dariah.jpg
