##########
# HATIRAT — Hatıratlar Dijital Kataloğu
# CollectionBuilder _config.yml
##########

##########
# SITE SETTINGS
#
title: Hatırat Portalı
tagline: Türk Hatırat Yazarlığı Dijital Kataloğu
description: "Bu katalog, Türkiye'deki hatırat yazarlığını yazar, tür, dönem ve mekâna göre aranabilir biçimde sunar."
author: DBB-M

##########
# URL SETTINGS
#
url: https://dbb-m.github.io
baseurl: /Hatirat
source-code: https://github.com/DBB-M/Hatirat

##########
# COLLECTION SETTINGS
#
metadata: hatirat_cb_ready

##########
# COLLECTION OBJECT DISPLAY
#
format-field: subject

latitude-field: latitude
longitude-field: longitude

date-field: date

subject-field: subject
location-field: place_of_birth

country-field: period

##########
# JEKYLL SETTINGS
#
exclude:
  - CITATION.cff
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - README.md
  - Rakefile
  - docs/
  - vendor/

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

optional_front_matter:
  remove_originals: true

readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

##########
# LIQUID
#
liquid:
  error_mode: warn
  strict_filters: false

##########
# MARKDOWN
#
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 2..3
